### ISSUE TITLE
System.InvalidOperationException: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.

### ISSUE THREAD

**Issue by stephen-swensen** [guryanovev/CrystalQuartz#87]
Getting this error at startup with ASP.NET Core 3.1 / WebAPI 

```
System.InvalidOperationException: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at CrystalQuartz.WebFramework.Request.AbstractFileRequestHandler.<>c__DisplayClass4_0.<WriteResourceToStream>b__0(Stream outputStream)
   at CrystalQuartz.AspNetCore.AspNetCoreResponseRenderer.Render(Response response)
   at CrystalQuartz.WebFramework.RunningApplication.Handle(IRequest request, IResponseRenderer renderer)
   at CrystalQuartz.AspNetCore.CrystalQuartzPanelMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by MatijaSestak** [comment]
Add 
`services.Configure<IISServerOptions>(options =>
    {
        options.AllowSynchronousIO = true;
    });`

to ConfigureServices method in Startup.cs

**Comment by alex-erygin** [comment]
+

**Comment by stephen-swensen** [comment]
Thanks - I'm no longer in a position to verify whether this works, but I'll trust it does and close this issue.

**Comment by Timovzl** [comment]
Configuring Kestrel to `AllowSynchronousIO` is a workaround, not a solution.
